name: dizifun Scripts (TRT 00:00)

on:
  schedule:
    # GitHub Actions CRON UTC çalışır. İstanbul 00:00 = UTC 21:00
    - cron: "0 21 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: m3u
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set timezone (Europe/Istanbul)
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo ln -fs /usr/share/zoneinfo/Europe/Istanbul /etc/localtime
          echo "Europe/Istanbul" | sudo tee /etc/timezone
          date

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            m3u/requirements.txt

      - name: Install dependencies (use requirements.txt if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # fallback: en azından gerekli paketleri kur
            pip install aiohttp beautifulsoup4
          fi

      - name: Run scripts
        run: |
          python "./Amazon Prime.py"
          python "./Blutv.py"
          python "./Disney+.py"
          python "./Exxen.py"
          python "./Gain.py"
          python "./HBO Max.py"
          python "./Hulu.py"
          python "./Netflix.py"
          python "./Paramount+.py"
          python "./Tabii.py"
          python "./TOD TV.py"
          python "./Unutulmaz Diziler.py"

      - name: Commit & push results (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update M3U outputs ($(date +'%Y-%m-%d %H:%M:%S %Z'))"
            git push
          else
            echo "No changes to commit."
          fi
