# Bu workflow, her 5 saatte bir veya manuel olarak tetiklendiğinde çalışır.
name: Generate and Deploy M3U Lists

on:
  schedule:
    # "0 */5 * * *" = Her 5 saatte bir çalıştır.
    - cron: "0 */5 * * *"
  workflow_dispatch: {} # Manuel olarak da tetikleyebilmek için

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Adım: Gizli deponun (Dizifun) kodlarını indirir.
      - name: Checkout Private Repo
        uses: actions/checkout@v4

      # 2. Adım: Python 3.11 ortamını kurar.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # 3. Adım: Gerekli Python kütüphanelerini kurar.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Adım: M3U dosyalarını oluşturan tüm Python script'lerini çalıştırır.
      - name: Run Python Scripts to Generate M3U
        run: |
          python "Amazon Prime.py"
          python "Blutv.py"
          python "Disney+.py"
          python "Exxen.py"
          python "Gain.py"
          python "HBO Max.py"
          python "Hulu.py"
          python "Netflix.py"
          python "Paramount+.py"
          python "Tabii.py"
          python "TOD TV.py"
          python "Unutulmaz Diziler.py"

      # 5. Adım: Oluşturulan dosyaları açık depoya (F-n) gönderir.
      - name: Push generated files to Public Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # Kurulumda oluşturduğumuz gizli anahtarı burada kullanıyoruz.
          SSH_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        with:
          # Script'lerin oluşturduğu dosyaların bulunduğu klasör (ana dizin)
          source-directory: '.'
          # Hedef depo bilgileri
          destination-github-username: 'ahmet21ahmet'
          destination-repository-name: 'F-n'
          # Hedef branch
          target-branch: main
          # Gönderen kullanıcı bilgileri
          user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          user-name: "github-actions[bot]"
          # Sadece .m3u ve .txt uzantılı dosyaları gönder
          file-pattern: |
            *.m3u
            *.txt
          # Commit mesajı
          commit-message: "Auto-update M3U lists"
